### PR TITLE
Implement compute_output_shape for BaseDenseAttention

### LINKED ISSUE #15719: Implement `compute_output_shape` for `BaseAttentionLayer`
**System information**
- TensorFlow version (you are using): 2.8
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
Currently the method compute_output_shape is not implemented for layers derived from `BaseAttentionLayer`. Hence, it's impossible to use these layers with, for example, `TimeDistributed` wrapper (see [issue](https://github.com/keras-team/keras/issues/15515) Attention module not working with TimeDistributed layer).
To fix this, one could use eager mode or implement some workaround. Another way is to implement `compute_output_shape` method for `BaseAttentionLayer`. But `BaseAttentionLayer.call` method has a parameter `return_attention_weights` that adds attention weights tensor to values returned by attention layer, if set. It could change output shape of the layer after build.
Moreover, parameter `return_attention_weights` does not change a state of the layer when provided and is not saved to the object's attributes. So, it's impossible to implement `compute_output_shape` method while `return_attention_weights` belongs to the parameters of the call method. 

My suggestion is to change the API like this:

from 
```python3
class BaseDenseAttention(Layer):
    def __init__(self, causal=False, dropout=0.0,
                 **kwargs):
      ...
    
    def call(self,
             inputs,
             mask=None,
             training=None,
             return_attention_scores=False):
      ...
```

to

```python3
class BaseDenseAttention(Layer):
    def __init__(self, causal=False, dropout=0.0, return_attention_scores=False),  # move the parameter to the constructor
                 **kwargs):
      self.return_attention_scores=return_attention_scores
      ...
    
    def call(self, 
             inputs,
             mask=None,
             training=None,
             return_attention_scores=False):   # <- make it deprecated and add deprecation warning, remove in future versions
      ...

  def compute_output_shape(self, input_shape):
      # this function returns output shape using self.return_attention_scores as a conditional 
      ...

These changes make computation of output shape possible, but keep the possibility to return attention weights, if it's necessary for model debugging and/or analysis. For most use cases, it's enough to place `return_attention_scores` in a constructor of a class. Likewise, in other keras layers the parameters that change output shape of the layer are placed in a constructor of the layer (for example, `return_sequences` in recurrent layers). 
```

Related issues:
- [Unable to create](https://github.com/keras-team/keras/issues/15515) TimeDistributed wrapper for Attention layers
- [Feature request](https://github.com/tensorflow/tensorflow/issues/44127) for the parameter `return_attention_weights` to the `call` method. 

**Will this change the current api? How?**
Parameter return_attention_weights will be moved from call method of BaseAttentionLayer layers to constructor of BaseAttentionLayer. That allows to compute output shape of the attention layers and use them with, for example, TimeDistributed wrapper (that fixes previously mentioned issue).

**Who will benefit with this feature?**
Anyone who would use attention layers.

**Any Other info.**
It could break some of the tutorials/examples. Fixes may be required in the future: [this NMT tutorial](https://github.com/tensorflow/text/blob/master/docs/tutorials/nmt_with_attention.ipynb) uses `return_attention_scores` parameter.

### PR DESCRIPTION
**Pull request by mishc9**
Resolves #15719

### CODE REVIEW

File: keras/layers/dense_attention.py [hunk 1]
```diff
@@ -40,6 +41,9 @@ class BaseDenseAttention(base_layer.BaseRandomLayer):
       flow of information from the future towards the past.
     dropout: Float between 0 and 1. Fraction of the units to drop for the
       attention scores.
+    return_attention_scores: bool, if `True`, layer returns the attention scores.
+      If `True`, the layer is incompatible with TimeDistributed wrapper.
```
Comment (qlzh727) [inline keras/layers/dense_attention.py:45]: If this change is purely trying to address the usage of TimeDistributed layer, then how about just let compute_output_shape() to assume return_attention_scores is False?

Moving this call param to init is a quite big API contract change (even we are just marking it as deprecated), there are many lib down the stream that is also using this as a call arg, and the migration effort to make it a call arg is potentially big.

**Review by qlzh727 — CHANGES_REQUESTED** [review]

File: keras/layers/dense_attention.py (hunk 1 above)
Comment (mishc9) [reply keras/layers/dense_attention.py:45]: Hm, looks like this is the way to solve the issue; but I'm not sure if it's okay to return tensor(s) with shapes that differ from the shape returned by `compute_output_shape`. It would not cause any problems programmatically, but might cause a problem with interpretation of how the layer works. It would confuse user in some (rare) cases:

```python3
attention_layer = keras.layers.Attention()
result, scores = attention_layer([[query_input, value_input], return_attention_scores=True)
res_output_shape, scores_shape = attention_layer.comute_output_shape()  # a user might expect shapes for both attention tensor and weights, but will get an error;
```
We could overcome this by adding a parameter `return_attention_scores` to the `compute_output_shape`, but it introduces a discrepancy between a method of this layer and the rest of keras layers. It seems to me that it's a bad change.
The second problem I expect if one will try to use returned attention weights as an input to the next layer in a Functional model. `compute_output_shape`  will return a value which is different from the actual output. I've not checked yet, but it looks like it would cause a model compilation error. Unfortunately, it's impossible to provide a `return_attention_scores` directly to the `attention_layer.compute_output_shape` method, because it requires unacceptable amount of (excessive for anything else) changes. 

So that I decided to move `compute_output_shape` to the constructor, realising that this is a significant API change.

Also there's a second reason for this merge request, because I'm not purely addressing the usage of TimeDistributed layer. This parameter was originally introduced in [this](https://github.com/tensorflow/tensorflow/issues/44127) feature request. But it seems to me that the solution wasn't optimal. `BaseDenseAttention.call` method has parameters that change output shape of the method. But for the rest of the layers parameters that could cause such changes are placed in a layer's constructor. And in this request I apply the same 'idea' to the `BaseDenseAttention`.

--
Considering this, I need a guidance if I should add changes you suggested or it's better to close PR (because original issue about TimeDistributed layer was resolved).

Comment (mishc9) [reply keras/layers/dense_attention.py:44]: So, I've made this change: `compute_output_shape` assumes that `return_attention_scores` is False.

File: keras/layers/dense_attention.py [hunk 2]
```diff
@@ -180,6 +180,9 @@ def compute_mask(self, inputs, mask=None):
       return tf.convert_to_tensor(q_mask)
     return None
 
+  def compute_output_shape(self, input_shape):
+    return tf.TensorShape(input_shape[0])
```
Comment (qlzh727) [inline keras/layers/dense_attention.py:184]: Please add a comment about ignoring the `return_attention_scores`

**Review by qlzh727 — APPROVED** [review]
Thanks for the fix.

File: keras/layers/dense_attention.py (hunk 1 above)
Comment (qlzh727) [reply keras/layers/dense_attention.py]: Thanks, for compute_output_shape(), it is mostly used by the framework that is trying to infer the output shape in some corner case. Most of the time, caller will just use the __call__ method to get the output. So I think this change should be fine.

**Review by qlzh727 — APPROVED** [review]
