### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by clime** [keras-team/keras#14632]
Needed to do: `cp ./lib64/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py ./lib/python3.9/site-packages/keras/utils/generic_utils.py` in my virtualenv.

```
tensorflow-2.5.0rc3-cp39-cp39-manylinux2010_x86_64.whl
Keras-2.4.3-py2.py3-none-any.whl
Python 3.9.4
```

**Comment by nzw0301** [comment]
dear keras-team, do you have any plan to release a newer stable version of Keras? Currently, the stable Keras `2.4.0` does not work with TensorFlow `2.5.0`.

**Comment by Nikeshbajaj** [comment]
Same issue here, with tensoflow 2.5.0, updated verion of keras doesn't work. Any plans to fix this issue.

**Comment by YiminGao0113** [comment]
Same issue here!

**Comment by JamesAngGIT** [comment]
same issue

**Comment by a0s** [comment]
same issue here with `plaidbench keras mobilenet`  (as described in https://www.micah.soy/posts/machine-learning-ai-on-macos-catalina-with-metal-gpu-support/)

**Comment by SpeedyCraftah** [comment]
same here with a standard keras installation

**Comment by zaid-kamil** [comment]
same issue
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
`File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\streamlit\script_runner.py", line 338, in _run_script
    exec(code, module.__dict__)
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\app.py", line 11, in <module>
    from enhancer import resolution_dlss
File ".\enhancer.py", line 6, in <module>
    from keras.models import load_model
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\utils\__init__.py", line 26, in <module>
    from .vis_utils import model_to_dot
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\utils\vis_utils.py", line 7, in <module>
    from ..models import Model
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\models.py", line 10, in <module>
    from .engine.input_layer import Input
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\engine\__init__.py", line 3, in <module>
    from .input_layer import Input
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\engine\input_layer.py", line 7, in <module>
    from .base_layer import Layer
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\engine\base_layer.py", line 12, in <module>
    from .. import initializers
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
File "C:\Users\xaidi\GitHub\Image-resolution-enhancer-using-DLSS\tf25\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(`

keras == 2.4.3
tensorflow==2.5.0
![image](https://user-images.githubusercontent.com/5492621/119300611-b005bf80-bc7e-11eb-86ad-fdeeeff9b743.png)

**Comment by khanfarhan10** [comment]
Replaced everything of `keras` to `tf.keras` ! 
Using Libs:
```
tensorflow-cpu==2.4.0
keras==2.4.0
```

```
import tensorflow as tf
from tensorflow import keras
```

Change layers as :

```
keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
```
Change Optimizer:
```
keras.optimizers.Adam(lr=1e-5)
tf.keras.optimizers.Adam(lr=1e-5)
```
Change Operations:
```
keras.concatenate
tf.concat
keras.flatten
tf.keras.flatten
keras.sum
tf.keras.sum
```

**Comment by khanfarhan10** [comment]
Trust me the above might be a long solution but will work in the long run.

**Comment by aliwelchoo** [comment]
I've gotten around this by uninstalling keras and changing anything I import from keras to instead import from tensorflow.keras

So this:

```
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import VGG16
```

became this: 
```
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.applications.vgg16 import decode_predictions
from tensorflow.keras.applications.vgg16 import VGG16
```

and then I didn't have to amend the rest of my work

**Comment by BetterRiven** [comment]
same issue when import hyperas

**Comment by ioneliabuzatu** [comment]
Had the same issue, after I uninstalled all tensorflows and keras-nightly, I reinstalled tensorflow with `pip install tensorflow --upgrade --force-reinstall` and it worked.

**Comment by a0s** [comment]
@aliwelchoo The `tensorflow.keras` works fine, but using `keras` directly is the only way to get `plaidml-keras` and using Metal and AMD GPU during learning on Mac

**Comment by Joo-Hyun** [comment]
`# import tensorflow.compat.v2 as tf
import tensorflow as tf
from tf import keras
.
tf.keras.generic_utils.populate_dict_with_module_objects(
@keras_export('keras.initializers.serialize')
def serialize(initializer):
  return tf.keras.generic_utils.serialize_keras_object(initializer)


@keras_export('keras.initializers.deserialize')
def deserialize(config, custom_objects=None):
  """Return an `Initializer` object from its config."""
  populate_deserializable_objects()
  return tf.keras.generic_utils.deserialize_keras_object(
      config,
      module_objects=LOCAL.ALL_OBJECTS,
      custom_objects=custom_objects,
      printable_module_name='initializer')

.

`

**Comment by Joo-Hyun** [comment]
I changed the tensorflow library import and changed the all .generic_utils.populate_dict_with_module_objects

**Comment by MatthiasRakotomalala** [comment]
same issue

**Comment by Jeevanvarmap** [comment]
replace: `import keras.utils as generic_utils`

with: `import tensorflow.python.keras.utils as generic_utils`

**Comment by Ammyvijay** [comment]
from tensorflow.keras import Sequential
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense,LSTM

**Comment by Maximevdm** [comment]
I'm having trouble with keras_self_attention import SeqSelfAttention. 
It gives the error: 
generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

Does someone know how to solve this problem?

**Comment by anasfathi0** [comment]
> Replaced everything of `keras` to `tf.keras` !
> Using Libs:
> 
> ```
> tensorflow-cpu==2.4.0
> keras==2.4.0
> ```
> 
> ```
> import tensorflow as tf
> from tensorflow import keras
> ```
> 
> Change layers as :
> 
> ```
> keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
> tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
> ```
> 
> Change Optimizer:
> 
> ```
> keras.optimizers.Adam(lr=1e-5)
> tf.keras.optimizers.Adam(lr=1e-5)
> ```
> 
> Change Operations:
> 
> ```
> keras.concatenate
> tf.concat
> keras.flatten
> tf.keras.flatten
> keras.sum
> tf.keras.sum
> ```

can someone explain to how to do this, i still new and do not understand

**Comment by wings-cofandt** [comment]
Yes it worked for me thanks everyone. Replacing keras with tensorflow.keras will definitely run your program

**Comment by khanfarhan10** [comment]
@anasfathi0 Instead of using the `keras` library explicitly, use `tensorflow` backend and call `keras` implicitly.

**Comment by wings-cofandt** [comment]
Hi Farhan,

Yeah I did that and it worked. Thanks very much

**Comment by phaneendhra-ch** [comment]
This sorted me out.
I have uninstalled tensorflow, keras and keras-nightly 
and i have reinstalled again  tensorflow and keras only.
I hope this might be helpful.

**Comment by wings-cofandt** [comment]
Thanks for responding, I used tensorflow.keras instead of keras and it
worked

**Comment by Dangape** [comment]
> 
> 
> I've gotten around this by uninstalling keras and changing anything I import from keras to instead import from tensorflow.keras
> 
> So this:
> 
> ```
> from keras.preprocessing.image import load_img
> from keras.preprocessing.image import img_to_array
> from keras.applications.vgg16 import preprocess_input
> from keras.applications.vgg16 import decode_predictions
> from keras.applications.vgg16 import VGG16
> ```
> 
> became this:
> 
> ```
> from tensorflow.keras.preprocessing.image import load_img
> from tensorflow.keras.preprocessing.image import img_to_array
> from tensorflow.keras.applications.vgg16 import preprocess_input
> from tensorflow.keras.applications.vgg16 import decode_predictions
> from tensorflow.keras.applications.vgg16 import VGG16
> ```
> 
> and then I didn't have to amend the rest of my work

This really solved the problem here! Thankssss

**Comment by RichardRosero** [comment]
e presentado los mismos errores logre solucionarlo con > 👍    pip install tensorflow --upgrade --force-reinstall  < el cual puso un desarrollador mas arriba uso, dando como resultado un> 👍  keras-nightly-2.5.0.dev2021032900    el cual funciona a la perfeccion
trabajo con las versiones de :
python 3.7.9
pip 21.1.2

exitos a todos

**Comment by matthewlehew** [comment]
I'm not sure the status of solving the underlying issue(s) for this bug, but something I've discovered is that the order of installing packages matters here. When creating a new virtual environment (Python 3.8), using the following command

`pip install keras tensorflow pillow`

results in the traceback below when importing some modules. However, if you instead do:

```
pip install keras
pip install tensorflow
pip install pillow
```

the error doesn't occur.

Traceback:

```
 File "imgTest.py", line 2, in <module>
    from keras.preprocessing import image
  File "/Users/matthewlehew/Developer/googleimages/imageprojectvenv/lib/python3.8/site-packages/keras/__init__.py", line 20, in <module>
    from . import initializers
  File "/Users/matthewlehew/Developer/googleimages/imageprojectvenv/lib/python3.8/site-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/Users/matthewlehew/Developer/googleimages/imageprojectvenv/lib/python3.8/site-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```

**Comment by aymanai** [comment]
> Replaced everything of `keras` to `tf.keras` !
> Using Libs:
> 
> ```
> tensorflow-cpu==2.4.0
> keras==2.4.0
> ```
> 
> ```
> import tensorflow as tf
> from tensorflow import keras
> ```
> 
> Change layers as :
> 
> ```
> keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
> tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
> ```
> 
> Change Optimizer:
> 
> ```
> keras.optimizers.Adam(lr=1e-5)
> tf.keras.optimizers.Adam(lr=1e-5)
> ```
> 
> Change Operations:
> 
> ```
> keras.concatenate
> tf.concat
> keras.flatten
> tf.keras.flatten
> keras.sum
> tf.keras.sum
> ```

Excellent it works, I just replace my import code only as

from tensorflow import keras 
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Activation

instead of 
# from keras import backend as K
# from keras.layers import Activation

**Comment by immanuelweule** [comment]
> 
> 
> Had the same issue, after I uninstalled all tensorflows and keras-nightly, I reinstalled tensorflow with `pip install tensorflow --upgrade --force-reinstall` and it worked.

THANK YOU SO MUCH!!!! YOU'RE A GOD!!

**Comment by mgioioso** [comment]
> Replaced everything of `keras` to `tf.keras`

This is the way to go. Tensorflow will ensure the compatibility with keras if you use the sub-package.

**Comment by Well2333** [comment]
same issue here QwQ

**Comment by Well2333** [comment]
> Yes it worked for me thanks everyone. Replacing keras with tensorflow.keras will definitely run your program

THANKSSSSSS, IT WORK!!!!!!

**Comment by BertramGilfoyle1** [comment]
If you work on ubuntu and conda:
> cp ./anaconda3/envs/tensorrt_2/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py ./anaconda3/envs/tensorrt_2/lib/python3.9/site-packages/keras/utils/generic_utils.py

**Comment by execptionerror** [comment]
[[Already Solved] AttributeError: module ‘keras.utils.generic_utils’ has no attribute ‘populate_dict_with_module_objects’
](https://exerror.com/attributeerror-module-keras-utils-generic_utils-has-no-attribute-populate_dict_with_module_objects/)

**Comment by nschang** [comment]
Solved on google Colab (CUDA==11.0; tensorflow==1.15) by adding `tensorflow.python.` to `keras.` in import:

```
# NOT WORKING
>>> from keras.initializers import initializers_v1
>>> from keras.initializers import initializers_v2
>>> from keras.utils import generic_utils
>>> from keras.utils import tf_inspect as inspect
```
this gives an error: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-fa830678264f> in <module>()
----> 1 from keras.utils import generic_utils
      2 from tensorflow.python.keras.utils import tf_inspect as inspect

8 frames
/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py in populate_deserializable_objects()
     80     v2_objs = {}
     81     base_cls = initializers_v2.Initializer
---> 82     generic_utils.populate_dict_with_module_objects(
     83         v2_objs,
     84         [initializers_v2],

AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```
this works: 
```
>>> from tensorflow.python.keras.initializers import initializers_v1
>>> from tensorflow.python.keras.initializers import initializers_v2
>>> from tensorflow.python.keras.utils import generic_utils
>>> from tensorflow.python.keras.utils import tf_inspect as inspect
```

**Comment by Abdurrasith** [comment]
> Replaced everything of `keras` to `tf.keras` !
> Using Libs:
> 
> ```
> tensorflow-cpu==2.4.0
> keras==2.4.0
> ```
> 
> ```
> import tensorflow as tf
> from tensorflow import keras
> ```
> 
> Change layers as :
> 
> ```
> keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
> tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
> ```
> 
> Change Optimizer:
> 
> ```
> keras.optimizers.Adam(lr=1e-5)
> tf.keras.optimizers.Adam(lr=1e-5)
> ```
> 
> Change Operations:
> 
> ```
> keras.concatenate
> tf.concat
> keras.flatten
> tf.keras.flatten
> keras.sum
> tf.keras.sum
> ```

Where and what is the file i must edit this?

**Comment by Gabriel0598** [comment]
Hello, i updated the TensorFlow through Anaconda Prompt with command line: `pip install tensorflow --update`, after it is in version 3.1.1. With it the problem was solved, it in my case, because i'm using the tensorflow through Anaconda platform.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to post a new issue if still have problems. Thanks!

**Comment by mdrhmn** [comment]
> I'm having trouble with keras_self_attention import SeqSelfAttention.
> It gives the error:
> generic_utils.populate_dict_with_module_objects(
> AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
> 
> Does someone know how to solve this problem?

Have you managed to solve the issue?

**Comment by eman85** [comment]
pip install keras-self-attention==0.50.0 

this is works for me

**Comment by yoyoisaboy** [comment]
from keras.utils import np_utils
change
from keras.utils.np_utils import *

**Comment by ravi-aii** [comment]
Reinstalling the tensorflow solved my same issue
pip install tensorflow --upgrade --force-reinstall --user

**Comment by mikechen66** [comment]
Please add the snippet of the code into the program of general_utils.py

**1. Find out your path**

For me, the path is listed as follows:

/home/user/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py

**2. Paste the code into the program of generic_utils.py**

def populate_dict_with_module_objects(target_dict, modules, obj_filter):
  for module in modules:
    for name in dir(module):
      obj = getattr(module, name)
      if obj_filter(obj):
        target_dict[name] = obj

**3. Initialize the dev tool**

It will be working after initializing the dev tool (it is Terminal for me in Linux)
