### PR TITLE
Skip channels_last is_contiguous under torch.vmap in conv

### LINKED ISSUE #23587: `torch.vmap` fails on nightly but runs on older version
The following works on keras `3.13.2` but fails `3.16.0.dev2026090404` nightly.

```python
import os
os.environ["KERAS_BACKEND"] = "torch"

import torch
import keras
from keras import ops

print("Keras:", keras.__version__)
print("Torch:", torch.__version__)
print("Backend:", keras.config.backend())

def conv_one(sample):
    sample = ops.expand_dims(sample, axis=0)  # (1, D, H, W, C)
    kernel = ops.ones((3, 3, 3, 1, 1), dtype="float32")
    return ops.conv(sample, kernel, padding="same")[0]

batch = ops.ones((2, 8, 8, 8, 1), dtype="float32")

try:
    result = ops.vectorized_map(conv_one, batch)
    print("vectorized_map: OK", ops.shape(result))
except Exception as error:
    print("vectorized_map: ERROR", type(error).__name__, error)
```
```
Keras: 3.13.2
Torch: 2.10.0+cu128
Backend: torch
vectorized_map: OK (2, 8, 8, 8, 1)
```

```
Keras: 3.16.0.dev2026090404
Torch: 2.10.0+cu128
Backend: torch
vectorized_map: ERROR RuntimeError NYI: querying is_contiguous inside of vmap for memory_format other than torch.contiguous_format
```

### PR DESCRIPTION
**Pull request by indrajeetapache**
## Summary

Fixes #23587.

`ops.vectorized_map` on the Torch backend still uses `torch.vmap`. After #22324, `channels_last` 2D/3D `ops.conv` calls `tensor.is_contiguous(memory_format=channels_last[_3d])` to pick a faster layout. PyTorch does not implement that query inside vmap:

```
RuntimeError: NYI: querying is_contiguous inside of vmap for memory_format other than torch.contiguous_format
```

That is why the reporter's 3D conv + `vectorized_map` example works on 3.13.2 (no layout conversion) and fails on nightly.

This PR keeps the eager channels-last optimization, and skips the conversion when `is_contiguous` raises the vmap NYI. Convolution is still correct because inputs are already transposed to Torch's channels-first layout; the memory-format conversion is only a performance hint.

Adds torch-only regression tests for 2D and 3D `channels_last` conv under `ops.vectorized_map`.

cc @mrinalghoshh @innat

## Test plan

- [x] New `ConvVectorizedMapTest` covers the reported 3D case and 2D `channels_last`
- [ ] CI: `keras/src/backend/torch/nn_test.py` on the torch backend

## Contributor Agreement

**Please review our [AI-Assisted Contribution Policy](../CONTRIBUTING.md#ai-assisted-contribution-policy) and check all boxes below before submitting your PR for review:**

- [x] I am a human, and not a bot.
- [x] I will be responsible for responding to review comments in a timely manner.
- [x] I will work with the maintainers to push this PR forward until submission.

### CODE REVIEW

**Review by divyashreepathihalli — APPROVED** [review]
Thank you for the fix!

**Review by divyashreepathihalli — COMMENTED** [review]
Please fix the failing tests.

**Review by hertschuh — CHANGES_REQUESTED** [review]
This seems related and was merged recently: https://github.com/keras-team/keras/pull/23199

Does it fix the problem?

If not, can you rebase on top of it and see if it fixes the tests?

**Comment by indrajeetapache** [comment]
Updated after the Torch CI failures and @hertschuh's note about #23199:

1. Rebased onto current master (includes #23199).
2. Guarded both layout sites that request `channels_last` / `channels_last_3d` memory format (`_transpose_spatial_inputs` and `_maybe_convert_to_channels_last`), falling back to default contiguous under the vmap NYI.
3. Fixed the regression tests to pass `data_format=\"channels_last\"` explicitly — that was the `groups=8` failure when CI ran with `channels_first`.

@divyashreepathihalli @hertschuh — ready for another look once CI is green.

File: keras/src/backend/torch/nn_test.py [hunk 1]
```diff
@@ -54,3 +54,49 @@ def test_compiled_matches_eager(self, is_causal, use_mask, use_bias, scale):
             compiled(query, key, value, **kwargs),
             ops.dot_product_attention(query, key, value, **kwargs),
         )
+
+
+@pytest.mark.skipif(
+    backend.backend() != "torch",
+    reason="This test is only applicable to the PyTorch backend.",
+)
```
Comment (hertschuh) [inline keras/src/backend/torch/nn_test.py:62]: Actually, can you try removing this.

In theory, it should work on all backends alike.

**Review by hertschuh — CHANGES_REQUESTED** [review]

**Comment by hertschuh** [comment]
But the code itself looks good, thanks!
