### PR TITLE
Sync verbose=1 with verbose=2

### PR DESCRIPTION
**Pull request by ozabluda**
... fixing (apparently) two bugs in verbose=2. verbose=1 logic was introduced in https://github.com/fchollet/keras/pull/704/ and https://github.com/fchollet/keras/commit/729f0765da577a4ebd879331f651b6d241a10632

### CODE REVIEW

**Comment by karantan** [comment]
You should probably squash the commits.

**Comment by ozabluda** [comment]
Commits are squashed automatically during PR merge.

**Comment by fchollet** [comment]
If this fixes a bug, can you please add a unit test (which would fail without with PR, and pass with it)?

**Comment by ozabluda** [comment]
The bug from https://github.com/fchollet/keras/commit/729f0765da577a4ebd879331f651b6d241a10632 is "obvious" and doesn't warrant a unit test, since there is no infrastructure to test it.

After looking at (what I called "apparently") bug where https://github.com/fchollet/keras/pull/704 logic is missing from verbose=2, the "bug" seems to me like a convoluted feature, likely not used by anyone, except the original author @rodrigob. Maybe it's best to remove it from verbose==1 rather then introduce it into verbose=2? But it would be an API change.

My stab at triggering the "feature":
```
class MyProgbar(Progbar):
        def __init__(self):
            Progbar.__init__(self,1,verbose=1)
            self.sum_values['MyETA']=1
            self.unique_values.append('MyETA')
            
mybar = MyProgbar()
mybar.update(1)

works:
1/1 [==============================] - 0s - MyETA: 1
```
but if you replace verbose=1 with verbose=2 it raises:
```
Traceback (most recent call last):
  File "./tests/keras/utils/generic_utils_test.py", line 36, in <module>
    test_progbar()
  File "build/bdist.linux-x86_64/egg/keras/utils/test_utils.py", line 157, in wrapper
  File "./tests/keras/utils/generic_utils_test.py", line 25, in test_progbar
    mybar.update(1)
  File "build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py", line 355, in update
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by ozabluda** [comment]
pep8 error was introduced in commit https://github.com/fchollet/keras/commit/7fc5466f95e2f9e19c8ab7602286f642a136091b (merged into this branch from master to resolve conflict)
