### ISSUE TITLE
transfer learning model based on universal sentence encoder cannot save to tf model for tensorflow serving

### ISSUE THREAD

**Issue by jacksonfengwa** [keras-team/keras#15145]
The model is created using the following codes,

model = tf.keras.models.Sequential()

model.add(hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4", input_shape=[], output_shape=[512], dtype=tf.string, trainable=False))

model.add(tf.keras.layers.Dense(10, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',
          loss='binary_crossentropy',
          metrics=['accuracy'])
......
model.fit(X_train, Y_train, epochs=1, validation_data=(X_test, Y_test))
model.save(model_save_loc)
......

I tried tensorflow 2.5.0 and 2.2.0. Both gave me the following exception when I saved the model after fully training it, (model training works perfectly)

Traceback (most recent call last):
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py", line 277, in del
self._destroy_resource()
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in call
result = self._call(*args, **kwds)
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call
results = self._stateful_fn(*args, **kwds)
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3022, in call
filtered_flat_args) = self._maybe_define_function(args, kwargs)
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
graph_function = self._create_graph_function(args, kwargs)
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
func_graph_module.func_graph_from_py_func(
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
func_outputs = python_func(*func_args, **func_kwargs)
File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
out = weak_wrapped_fn().wrapped(*args, **kwds)
AttributeError: 'NoneType' object has no attribute 'wrapped'

**Comment by qlzh727** [comment]
Assign to Kathy for save model issue.

**Comment by jacksonfengwa** [comment]
It seems to be working in tensorflow 2.6. closing it.
