### ISSUE TITLE
module 'keras.preprocessing' has no attribute 'text'

### ISSUE THREAD

**Issue by dma092** [keras-team/keras#8715]
I am getting this error when trying to use the text preprocessing features with keras.
module 'keras.preprocessing' has no attribute 'text'

`
from keras import preprocessing
result=preprocessing.text.text_to_word_sequence(data['sentence'],
                                               filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
                                               lower=True,
                                               split=" ")`

**Comment by vitaly-krumins** [comment]
You have to import the module slightly differently.
Try this instead:
`from keras.preprocessing import text`
`result = text.text_to_word_sequence(data['sentence'])`

**Comment by sohamshashank1** [comment]
from keras.preprocessing import text
This works well

**Comment by isaacmg** [comment]
Yes I have this same issue. But I do not want to the from statement as I'm dynamically loading keras as a variable.

**Comment by fchollet** [comment]
Both of these import patterns work fine with Keras 2.1.6 (and 2.2.0).

**Comment by ShebahD** [comment]
Oh, I have the similar issue ,the IDE throws 'AttributeError : module 'preprocessing' has no attribute 'sequence''.I've tried some ways but they donot work!

**Comment by Abusiddik03** [comment]
Hi @fchollet 

I am facing similar issue, i'm using Keras 2.2.4. any suggestions?
AttributeError: module 'keras_preprocessing.text' has no attribute 'tokenizer_from_json'

**Comment by abdul8177** [comment]
@ShebahD  Try to import this line "from keras.preprocessing import sequence"

**Comment by MohammadHeydari** [comment]
> You have to import the module slightly differently.
> Try this instead:
> `from keras.preprocessing import text`
> `result = text.text_to_word_sequence(data['sentence'])`

Workes fine. Thanks
