### ISSUE TITLE
AttributeError in ZIP extraction: 'ZipInfo' object has no attribute 'name' (introduced in #21760)

### ISSUE THREAD

**Issue by wenwen-666** [keras-team/keras#22479]
After PR #21760 (which added safe archive extraction logic), calling extract_open_archive with a ZIP archive immediately raises anAttributeError: AttributeError: 'ZipInfo' object has no attribute 'name'

This breaks ZIP extraction for model loading, weights, and datasets. The error comes from using finfo.name in filter_safe_zipinfos, while ZipInfo only has finfo.filename.

Expected Behavior
1. Safe files should extract normally
2.Unsafe paths should be skipped with a warning
3.No AttributeError during ZIP extraction

Steps to Reproduce：

import io
import zipfile
from keras.src.utils import file_utils

zip_buffer = io.BytesIO()
with zipfile.ZipFile(zip_buffer, "w") as zf:
    zf.writestr("test.txt", "sample content")
zip_buffer.seek(0)

with zipfile.ZipFile(zip_buffer, "r") as archive:
    file_utils.extract_open_archive(archive, path="./extracted_test")

Root Cause: Typo in keras/src/utils/file_utils.py → filter_safe_zipinfos uses finfo.name instead of finfo.filename.

Fixed Code:

def filter_safe_zipinfos(members):
    base_dir = resolve_path(".")
    for finfo in members:
        valid_path = False
        # Fix: replace .name with .filename for ZipInfo
        if is_path_in_dir(finfo.filename, base_dir):
            valid_path = True
            yield finfo
        if not valid_path:
            warnings.warn(
                "Skipping invalid path during archive extraction: "
                f"'{finfo.filename}'.",
                stacklevel=2,
            )

**Comment by ChiragSW** [comment]
@wenwen-666 the fixed code seems to be the solution for the issue as it no longer raises AttributeError. 

should I put up a PR? as it seems to be a minimal fix.

**Comment by wenwen-666** [comment]
@ChiragSW  Of course! That would be great. Thank you for looking into a minimal backward‑compatible fix.

**Comment by dhantule** [comment]
Hi @wenwen-666, 

I have tested this issue with Keras 3.13.2, it's working fine in this [gist](https://colab.sandbox.google.com/gist/dhantule/3b9a8c0d5b2eeccb3342d840100c1c9d/attributeerror-in-zip-extraction-zipinfo-object-has-no-attribute-name-introduced-in-21760-22479.ipynb).

**Comment by wenwen-666** [comment]
@dhantule  Thanks for checking! The difference comes from specific upstream PR changes between versions. 
It is a behavioral regression triggered under slightly different argument combinations, not plain Keras base usage.

**Comment by whitakercaleb09-dev** [comment]
Thanks for providing the additional context regarding the behavioral
regression.

**Comment by Saumay** [comment]
Looks like this is already fixed on current master (e94cb07d5) by #22480. The repro now extracts cleanly without AttributeError. Probably safe to close.
