### ISSUE TITLE
import keras error: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by bergen288** [keras-team/keras#14995]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows Server 2016
- TensorFlow installed from (source or binary): tensorflow-cpu from PYPI.
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.8.8
- Bazel version (if compiling from source):
- GPU model and memory: No GPU, 64GB memory.
- Exact command to reproduce: import keras
- protobuf version: 3.17.3 from PYPI
- conda version: 4.10.3

**Describe the problem**.
Failed when trying to import keras.

**Describe the current behavior**.
Failed when trying to import keras.

**Describe the expected behavior**.
"keras" should be import without error.
**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): No
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.
import keras

**Source code / logs**.
Traceback (most recent call last):
  File "e:\Python_Projects\examples\syspath.py", line 1, in <module>
    import keras
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py", line 25, in <module>
    from keras import models
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\metrics.py", line 27, in <module>
    from keras import activations
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 24, in <module>
    from keras.engine.input_layer import Input
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 43, in <module>
    from keras.saving.saved_model import layer_serialization
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 22, in <module>
    from keras.saving.saved_model import save_impl
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\saving\saved_model\save_impl.py", line 32, in <module>
    from keras.saving.saved_model import load as keras_load
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\saving\saved_model\load.py", line 27, in <module>
    from keras.protobuf import saved_metadata_pb2
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\protobuf\saved_metadata_pb2.py", line 14, in <module>
    from keras.protobuf import versions_pb2 as keras_dot_protobuf_dot_versions__pb2
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\protobuf\versions_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by sushreebarsa** [comment]
Could you please try to` import keras` using TF stable version 2.5.0 .I am not getting error reported while using TF v2.5.0, please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/65c7735a193c7b25ad2e410f2642d01f/untitled342.ipynb) for your reference..Thanks!

**Comment by bergen288** [comment]
I just figured out the root cause.  It's because of the inconsistent versions between protobuf (3.17.3) and libprotobuf (3.11.2).  The issue has been resolved after the upgrade of libprotobuf to 3.17.2.

Thanks.
