### ISSUE TITLE
AttributeError: 'LossScaleOptimizerV3' object has no attribute '_variables'

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18112]
## Issue 

With TF 2.11, the **mixed precision** and **model-checkpoint callback** don't work properly in combined. 

```python
import tensorflow as tf
from tensorflow import keras
keras.mixed_precision.set_global_policy("mixed_float16")

def get_model():
    model = keras.Sequential()
    model.add(keras.layers.Dense(1, input_dim=784))
    model.compile(
        optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
        loss="mean_squared_error",
        metrics=["mean_absolute_error"],
    )
    return model

# Load example MNIST data and pre-process it
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

model = get_model()
model.fit(
    x_train,
    y_train,
    batch_size=128,
    epochs=3,
    verbose=1,
    validation_split=0.5,
    callbacks=[keras.callbacks.ModelCheckpoint(filepath='model.h5')],
)
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 2
      1 model = get_model()
----> 2 model.fit(
      3     x_train,
      4     y_train,
      5     batch_size=128,
      6     epochs=3,
      7     verbose=1,
      8     validation_split=0.5,
      9     callbacks=[keras.callbacks.ModelCheckpoint(filepath='model.h5')],
     10 )

File /opt/conda/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /opt/conda/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py:775, in _BaseOptimizer.variables(self)
    773 def variables(self):
    774     """Returns variables of this optimizer."""
--> 775     return self._variables

AttributeError: 'LossScaleOptimizerV3' object has no attribute '_variables'
```

The code works in TF 2.10, 2.12. But to use TF 2.11, what are the fixes can be used here?

**Comment by tilakrayal** [comment]
@innat,
Have you got the chance to take a look at this related https://github.com/keras-team/keras/pull/17225 where the PR delegates **finalize_variable_values()** in `LossScaleOptimizerV3` to the wrapped optimizer and also it fixes the exponential moving averages when used together with mixed precision. Also please  take a look at this issue for reference.
https://github.com/keras-team/keras/issues/17275
Thank you!

**Comment by innat** [comment]
@tilakrayal 
Thanks for the update. https://github.com/keras-team/keras/issues/17275 and https://github.com/horovod/horovod/issues/3807 are similar. Both are closed as the issue don't appear in TF > 2.11. But to use TF 2.11, what are the fixes here?

**Comment by Frightera** [comment]
@innat 

Workarounds would be either:
1) Use the saved model format
2) Save the weights only
