### ISSUE TITLE
[reproduce] 'NoneType' object has no attribute 'raise_exception_on_not_ok_status'

### ISSUE THREAD

**Issue by iperov** [keras-team/keras#11751]
This bug has appeared when I upgraded keras from 2.1.6 to 2.2.2

tensorflow-gpu==1.11.0

exception on exit:
```
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x00000000144B6B00>>
Traceback (most recent call last):
  File "F:\DeepFaceLab\_internal\bin\lib\site-packages\tensorflow\python\client\session.py", line 1413, in __del__
AttributeError: 'NoneType' object has no attribute 'raise_exception_on_not_ok_status'
```

minimal reproduce
```
import numpy as np

#import keras   #<-- uncomment this to remove exception

def main():
    import keras
    
    bgr_shape = (64, 64, 3)
    inp = keras.layers.Input(bgr_shape)

    outp = keras.models.Model(inp, [inp])(inp)
    
    flow = keras.backend.function([inp],[outp])
    flow ( [np.zeros ( (1,64,64,3), dtype=np.float32 )] )
    
if __name__ == "__main__":    
    main()
```

when I downgrading back to 2.1.6, no exception occur.

and of course I cannot use global import keras, because I am using keras in multiprocessing

**Comment by iperov** [comment]
please fix it

**Comment by iperov** [comment]
PLEASE FIX IT

**Comment by iperov** [comment]
@gabrieldemarmiesse any news?

**Comment by iperov** [comment]
this code works fine

```
import sys
import numpy as np

def main():
    import tensorflow
    ####import keras
    keras = tensorflow.keras
    K = keras.backend
    KL = keras.layers

    bgr_shape = (64, 64, 3)
    inp = KL.Input(bgr_shape)
    outp = K.mean(inp)
    
    flow = K.function([inp],[outp])
    flow ( [np.zeros ( (1,64,64,3), dtype=np.float32 )] )

if __name__ == "__main__":    
    main()    

sys.exit()
```

so this is 100% keras issue
