### ISSUE TITLE
Tensorboard won't work

### ISSUE THREAD

**Issue by potato1992** [keras-team/keras#13680]
**System information**  
- OS Platform and Distribution (Linux Ubuntu 18.04):  
- TensorFlow backend (yes):  
- TensorFlow version:  2.1.0
- Keras version:  2.3.1
- Python version:  3.5
- CUDA/cuDNN version:  10.1.243/ 7604 (7.6.4)
- GPU model and memory:  MX150 2GB

**Describe the current behavior**  
When adding tensorboard callback, the training crashed
With the output:

Loading train / test dataset :  data/satellites/ data/satellites/
Finished processing train dataset..
Finished loading test dataset..

Number of train samples :  10954 Number of test samples :  5501
Number of classes :  2
Sequence length :  120
Class weights :  [1.46326476 0.75953405]
Train on 10954 samples, validate on 5501 samples
Traceback (most recent call last):
  File "/home/potato1992/.vscode/extensions/ms-python.python-2020.1.57204/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/potato1992/.vscode/extensions/ms-python.python-2020.1.57204/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/potato1992/.vscode/extensions/ms-python.python-2020.1.57204/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/potato1992/workspace/WindowsProjects/python/MLSTM-FCN/satellites_model.py", line 318, in <module>
    train_model(model, DATASET_INDEX, dataset_prefix='satellites', epochs=600, batch_size=128)
  File "/home/potato1992/workspace/WindowsProjects/python/MLSTM-FCN/utils/keras_utils.py", line 166, in train_model
    class_weight=class_weight, verbose=1, validation_data=(X_test, y_test))
  File "/home/potato1992/workspace/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/home/potato1992/workspace/venv/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 119, in fit_loop
    callbacks.set_model(callback_model)
  File "/home/potato1992/workspace/venv/lib/python3.6/site-packages/keras/callbacks/callbacks.py", line 68, in set_model
    callback.set_model(model)
  File "/home/potato1992/workspace/venv/lib/python3.6/site-packages/keras/callbacks/tensorboard_v2.py", line 116, in set_model
    super(TensorBoard, self).set_model(model)
  File "/home/potato1992/workspace/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 1532, in set_model
    self.log_dir, self.model._get_distribution_strategy())  # pylint: disable=protected-access
AttributeError: 'Model' object has no attribute '_get_distribution_strategy'
Terminated

**Code to reproduce the issue**  
model_checkpoint = ModelCheckpoint(weight_fn, verbose=1, mode=optimization_mode,
                                       monitor=monitor, save_best_only=True, save_weights_only=True)
reduce_lr = ReduceLROnPlateau(monitor=monitor, patience=100, mode=optimization_mode,
                                  factor=factor, cooldown=0, min_lr=1e-4, verbose=2)
tensorboard = TensorBoard(log_dir=("./logs/%s_%s")%(dataset_prefix,time()),histogram_freq=1)

##############################
#this code would cause the crash
#callback_list = [model_checkpoint, reduce_lr,tensorboard]
#this code would not cause the crash
callback_list = [model_checkpoint, reduce_lr]

optm = Adam(lr=learning_rate)

if compile_model:
    model.compile(optimizer=optm, loss='categorical_crossentropy', metrics=['accuracy'])

if val_subset is not None:
    X_test = X_test[:val_subset]
    y_test = y_test[:val_subset]

    model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, callbacks=callback_list,
              class_weight=class_weight, verbose=1, validation_data=(X_test, y_test))

**Other info / logs**  
It works fine with tensorflow2.0.0, but not with 2.1.0

**Comment by rafalschmidt97** [comment]
Hi, I have exactly the same problem.

Python 3.6.10
Tensorflow 2.1 (2.0.1 works)
macOS Catalina

It doesn't work even with - https://keras.io/examples/lstm_text_generation/
As @potato1992 said it's about Tensorboard. After adding it as callback it stops working.
