### ISSUE TITLE
clear_session() doesn't clear memory from GPU

### ISSUE THREAD

**Issue by nkumar15** [keras-team/keras#9379]
Apologies If I am not able to understand the obvious solution mentioned in other issues opened/closed for same problem,
However after reading the issues, I used clear_session and reset_default_graph function, but still its doesn't clear the memory.

Below is the code I am testing and at prompt Break2, I was expecting GPU memory to be released, but still it doesn't clear the memory.

Can somebody please shed some light, what wrong I am doing here?

Version tested on:
Tensorflow 1.5.0
CUDA 9.0
Keras 2.1.3 

```
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM
from keras import backend as be
 
import tensorflow as tf
 
config = tf.ConfigProto()
 
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.5 
be.tensorflow_backend.set_session(tf.Session(config=config))

model = Sequential()
model.add(Embedding(1000, output_dim=256))
model.add(LSTM(128))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))
 
model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

x = input("Break 1")
be.clear_session()
tf.reset_default_graph()
x = input("Break 2")
```

**Comment by pinkeshbadjatiya** [comment]
I also faced similar problem a few days back, Apparently, you cannot forcefully clear the GPU memory as it might cause fragmentation. Either the GPU clears it automatically, or if you want to do it, then you can kill the process and GPU handles the remains of the process.

**Comment by nkumar15** [comment]
Okay, I got your point, but it is strange that api is claiming it will clear the gpu memory.
Is there anything we misunderstood from clear_session() functionality?

**Comment by phobrain** [comment]
What if you reset the graph before clear_session?

**Comment by ldm314** [comment]
I have the same issue. TF 1.12.0, Keras 2.2.4.

Every iteration of the loop I save the weights to disk, clear the session, create new models and load the weights. After a dozen or so iterations, OOM errors.

<pre>
    def cleanup_memory(self):
        K.clear_session()
        del self.combined
        del self.discriminator
        del self.generator
        gc.collect()
</pre>

**Comment by phobrain** [comment]
del model

    K.clear_session()


    On Thursday, January 17, 2019, 5:20:59 PM PST, Brian Moore <notifications@github.com> wrote:  
 
 
I have the same issue. TF 1.12.0, Keras 2.2.4.

Every iteration of the loop I save the weights to disk, clear the session, create new models and load the weights. After a dozen or so iterations, OOM errors.
    def cleanup_memory(self):
        K.clear_session()
        del self.combined
        del self.discriminator
        del self.generator
        gc.collect()

**Comment by chg0901** [comment]
I have a answer from https://stackoverflow.com/a/52354943/7194271
Releasing RAM memory
For releasing the RAM memory, just do del Variables as suggested by @nuric in the comment.

Releasing GPU memory
This is a little bit trickier than releasing the RAM memory. Some people will suggest you the following code (Assuming you are using keras)

from keras import backend as K
K.clear_session()
However, the above code doesn't work for all people. (Even when you try del Models, it is still not going to work)

If the above method doesn't work for you, then try the following (You need to install the numba library first):

from numba import cuda
cuda.select_device(0)
cuda.close()
The reason behind it is: Tensorflow is just allocating memory to the GPU, while CUDA is responsible for managing the GPU memory.

If CUDA somehow refuses to release the GPU memory after you have cleared all the graph with K.clear_session(), then you can use the cuda library to have a direct control on CUDA to clear up GPU memory.

**Comment by Darkhunter9** [comment]
Cuda solution is very effective, except it will thoroughly clear everything in GPU, works for me.

**Comment by freepi** [comment]
@Darkhunter9 or anyone, how are you resetting Keras after cuda.close() so that you can continue using Keras in the same process?  I tried setting a new session but that just gave error "failed to memset memory: CUDA_ERROR_INVALID_VALUE"

**Comment by Darkhunter9** [comment]
> @Darkhunter9 or anyone, how are you resetting Keras after cuda.close() so that you can continue using Keras in the same process? I tried setting a new session but that just gave error "failed to memset memory: CUDA_ERROR_INVALID_VALUE"

In my project, I don't need to use Keras after cuda.close(). After running cuda.close(), I run some OpenCL code and that works fine.
I suppose you need to open a new TF session.
The ultimate solution may be running the whole TF model in a separate process (using Process in Python) and kill it after returning the output back to the main process. This works when I have multiple OpenCL sessions running simultaneously in individual processes.

**Comment by ben981** [comment]
> The ultimate solution may be running the whole TF model in a separate process (using Process in Python) and kill it after returning the output back to the main process. This works when I have multiple OpenCL sessions running simultaneously in individual processes.

I created a simple package that does exactly this (except relying on `multiprocessing` since in my experience it does not always free all the memory).

It's called `scriptifier` you can install it via `pip install scriptifier`

It automatically generates the script and takes care of passing the arguments and returns as long as they are pickleable or keras models or lists of keras models... (for documentation see: [github][1])

It should look like this:

```
from scriptifier import scriptifier

def func_1(in):
    ...
    model.fit()
    ...
    return out

scriptified_func_1 = scriptifier.run_as_script(func_1)
out = scriptified_func_1(in)
```

  [1]: https://github.com/ben981/scriptifier

Definetly not a solution but as a workaround it's reliable enough.

**Comment by moon341** [comment]
> > The ultimate solution may be running the whole TF model in a separate process (using Process in Python) and kill it after returning the output back to the main process. This works when I have multiple OpenCL sessions running simultaneously in individual processes.
> 
> I created a simple package that does exactly this (except relying on `multiprocessing` since in my experience it does not always free all the memory).
> 
> It's called `scriptifier` you can install it via `pip install scriptifier`
> 
> It automatically generates the script and takes care of passing the arguments and returns as long as they are pickleable or keras models or lists of keras models... (for documentation see: [github](https://github.com/ben981/scriptifier))
> 
> It should look like this:
> 
> ```
> from scriptifier import scriptifier
> 
> def func_1(in):
>     ...
>     model.fit()
>     ...
>     return out
> 
> scriptified_func_1 = scriptifier.run_as_script(func_1)
> out = scriptified_func_1(in)
> ```
> 
> Definetly not a solution but as a workaround it's reliable enough.

Hi be981,I am trying to use your module but it is giving me this error!!! any solutions for this???
AttributeError: module 'scriptifier.scriptifier' has no attribute 'run_as_script'

**Comment by ben981** [comment]
> Hi be981,I am trying to use your module but it is giving me this error!!! any solutions for this???
>AttributeError: module 'scriptifier.scriptifier' has no attribute 'run_as_script'

Thanks! It should be fixed now.
Update the package and you should be good to go :)

**Comment by moon341** [comment]
> > Hi be981,I am trying to use your module but it is giving me this error!!! any solutions for this???
> > AttributeError: module 'scriptifier.scriptifier' has no attribute 'run_as_script'
> 
> Thanks! It should be fixed now.
> Update the package and you should be good to go :)

I am getting this error now after updating the scriptifier package to 0.0.14.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-c586472f6917> in <module>
      9     return model,history
     10 scriptified_func_1 = scriptifier.run_as_script(func_1)
---> 11 out = scriptified_func_1()

D:\anaconda3\envs\py5\lib\site-packages\scriptifier\scriptifier.py in wrapper(*args, **kwargs)
    115         # Temporarily copy the module of the function in the package folder
    116         function_module = sys.modules[function.__module__]
--> 117         function_module_path = function_module.__file__
    118         final_module_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "temporary_module.py")
    119         file_copier(function_module_path, final_module_path)

AttributeError: module '__main__' has no attribute '__file__'
