### ISSUE TITLE
Reduce memory burden on small GPUs with "Physical/Virtual Batch Size"

### ISSUE THREAD

**Issue by kuza55** [keras-team/keras#5244]
Not sure if this is a great idea since I solved this problem for myself by buying a GPU with a lot of memory, but...

One of the ways that is suggested to get models running on smaller GPUs is by reducing the batch size, however given the fact that the batch size is meaningful for the optimization procedure as well as the actual execution, it may be useful to decouple the batches that gradients are computed with vs the batches that are used to do optimization steps, i.e. run several smaller physical batches where gradients are accumulated across batches before a gradient step is taken.

**Comment by tstandley** [comment]
+1
I think this is possible and could be implemented without too much fuss (though I haven't the setup right now). I think having a virtual_batch_size parameter in the optimizers might be a good API for this idea too.

**Comment by kuza55** [comment]
I don't think this would require any changes to optimizer APIs, this would just require gradients to be accumulated across multiple batches before passing them to the optimizer. I'm happy to do the implementation if there's some agreement that this is worthwhile.

**Comment by raghakot** [comment]
+1 Something like this would be very useful.

**Comment by raghakot** [comment]
@kuza55 Any pointers on how tp get started? I am currently trying to implement this..

**Comment by kuza55** [comment]
You would want to change the fit function to:

Allocate some space for the gradients, based on the size of the model's trainable weights.

Instead of running an op that computes gradients, passes them to an optimizer that computes steps and applies those to the weights, you'll want to run an op that applies those weights to your accumulation buffer.

On the final step in each virtual batch you'll want to run the accumulated gradients through an optimizer and then apply them to the weights.

You may need to change the model building code to build this accumulation/apply op, I think these graph ops get built before the fit function.

**Comment by arunpatala** [comment]
This would be a nice feature.

**Comment by nouiz** [comment]
Why not do as other optimizer? Like Adams optimizer out momentum? It is
like a momentum with special updates frequency. This could disrupt less
keras code base.

**Comment by kuza55** [comment]
I don't like the idea of a single separate optimizer, since this is totally orthogonal to which optimizer a person wants to use, and having to duplicate all the optimizers seems worse than making changes to the Keras codebase.

If it's possible to make a wrapper, or make some changes to the base class, that would be a fine solution.

It's probably possible to do most of what's desired with a wrapper by using a conditional graph op which counts how many rows it has accumulated before doing the update, though it would lose any incomplete virtual batches. Though I guess a wrapper could also have a callback function that you stick into the training callbacks that flushes the update when training is done.

That actually seems pretty reasonable.

**Comment by RaananHadar** [comment]
This should be orthogonal to the optimizer so new optimizers may use this. 
This is useful not only for people with 'small gpu's. Its a really useful feature because it allows you to use deeper models/larger batch.

**Comment by the-moliver** [comment]
I did this as a separate [optimizer](https://github.com/the-moliver/kfs/blob/master/optimizers.py#L9), but it would be better to have it as a feature for arbitrary optimizers.

**Comment by raghakot** [comment]
We still need a solution for this.

**Comment by VENHEADs** [comment]
Agree with that

**Comment by waleedka** [comment]
+1 This would be a great addition.

**Comment by rohit-gupta** [comment]
I would definitely welcome this feature.

**Comment by EmilHJ** [comment]
Was this ever implemented? I could really use this feature!

**Comment by chwang1985** [comment]
gradient_batch = []
    for index in range(batch_size):
        with tf.device("/device:GPU:{}".format(index % gpu_count)):
            output = feed_forward(...)
            loss = get_loss(output)
            gradient_batch.append(tf.gradients(loss, tf.trainable_variables()))
    with tf.device("/cpu:0"):
        update = tf.train.AdamOptimizer().apply_gradients(
            zip(
                [tf.reduce_mean(input_tensor=tf.stack(part_batch), axis=0) for part_batch in zip(*gradient_batch)],
                tf.trainable_variables()
            )
        )

**Comment by Phyx** [comment]
I'm looking for this awesome feature, too. No progress?
@erikchwang where would one have to add your code snippet, when starting from a keras typical fit_generator() call?

**Comment by ppwwyyxx** [comment]
This can be achieved easily by just wrapping any tensorflow optimizer with [AccumGradOptimizer](https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.optimizer.AccumGradOptimizer)

**Comment by Phyx** [comment]
This code runs and was supposed to do the job, but it performs totally worse compared to real mini_batches. Is there something that I need to take care of? @ppwwyyxx 

`from keras.models import Sequential
from keras.layers import Activation, Flatten, Dense, BatchNormalization, Conv2D, InputLayer, MaxPooling2D
import tensorflow as tf
from keras import optimizers
from tensorpack.tfutils.optimizer import AccumGradOptimizer

test_model = Sequential([
    InputLayer(input_shape=(128, 128, 3)),
    Conv2D(50, (5, 5), padding='valid'),
    Activation('relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(50, (5, 5), padding='valid'),
    Activation('relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    BatchNormalization(),
    Dense(30, activation="relu"),
    BatchNormalization(),
    Dense(2, activation='softmax')
])

tfopti = tf.train.AdamOptimizer()
tfopti = AccumGradOptimizer(tfopti, niter=16)
keras_opti = optimizers.TFOptimizer(tfopti)

test_model.compile(
    optimizer=keras_opti,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)`

**Comment by ppwwyyxx** [comment]
The code does what it says, and no one can guarantee you it will work better or worse

**Comment by tstandley** [comment]
What is the actual batch size you are setting? The code simulates a larger
minibatch for updates, but not for batchnorm. Small batches for batchnorm
can totally ruin performance because the batchnorm statistics aren't stable
enough.

**Comment by Phyx** [comment]
@tstandley thanks for your hint. Actual batch_size was 1. Removing the batchnorm layers did not help!

batch_size = 8 -> Optimization works, problem get solved close to perfectness.
batch_size = 1, niter=8 -> Optimization gets stuck at random guess accuracy.

Seems like, at least for this experiment, AccumGradOptimizer does not provide a virtual compensation for bigger batch size.

**Comment by tstandley** [comment]
Yes that makes sense. Batchnorm will not work with only one channel. You
can try batch size=4 and niter=2. That should work better and save nearly
half of the memory.

**Comment by sipposip** [comment]
The tensorpack solution does not work with tf >=2.0, unfortunately
```python
/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/optimizer.py in apply_gradients(self, grads_and_vars, global_step, name)
    190             slots_and_vars = [(s, gv[1]) for s, gv in zip(slots, grads_and_vars)]
    191 
--> 192             with tf.variable_scope(self._name), tf.device('/cpu:0'):
    193                 counter = tf.Variable(
    194                     0, name="counter", trainable=False, dtype=tf.int32)

AttributeError: module 'tensorflow' has no attribute 'variable_scope'
```
