### ISSUE TITLE
AttributeError coming from base_layer

### ISSUE THREAD

**Issue by thomaskelm** [keras-team/keras#13338]
**System information**  
- Have I written custom code (as opposed to using example directory):  no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  python:3.6-slim docker image (Debian) https://github.com/docker-library/python/blob/35566cb6b14961c369e935b85b4c8879e6901ccc/3.6/buster/slim/Dockerfile
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0
- Keras version:  2.3.0
- Python version:  3.6
- CUDA/cuDNN version:  N/A (running on cpu for inference)
- GPU model and memory:  N/A (running on cpu for inference)

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
I am trying to initialize a model and I am running into an error coming from the base_layer class. The same code was working in Keras 2.2.5, but is now breaking with Keras 2.3.0

It looks like the _thread._local object doesn't have a value
https://stackoverflow.com/questions/20640679/thread-local-object-has-no-attribute

**Describe the expected behavior**  
Initialize a model without this issue.

**Code to reproduce the issue**  

from keras.models import Model, Input
input_text = Input(shape=(self.max_len,), dtype="string")

**Other info / logs**  
Traceback (most recent call last):
    input_text = Input(shape=(50,), dtype="string")
  File "/usr/local/lib/python3.6/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/input_layer.py", line 40, in __init__
    super(InputLayer, self).__init__(dtype=dtype, name=name)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 110, in __init__
    self.input_spec = None
  File "/usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1215, in __setattr__
    if not _DISABLE_TRACKING.value:
AttributeError: '_thread._local' object has no attribute 'value'

The changes to keras base_layer that are currently causing this issue came from this commit:
https://github.com/keras-team/keras/commit/479fc3a978221bb835f7e2781dcef0db66c96e1c

**Comment by fchollet** [comment]
It sounds like you're using or defining a Keras model in multiple threads concurrently. Could you provide a complete runnable code snippet to reproduce the issue?

**Comment by fchollet** [comment]
I have fixed this issue on `master`. Please install from `master` and check.

**Comment by thomaskelm** [comment]
that has fixed that issue. Thanks for the quick turnaround!
