### ISSUE TITLE
Inconsistent type handling between backends: ops.sqrt

### ISSUE THREAD

**Issue by lbortolotti** [keras-team/keras#18400]
Sorry for the spam :-)

I'm migrating my codebase to exclusively use keras_core.ops methods, including all all "base" operations, based on feedback received in https://github.com/keras-team/keras-core/issues/919 and others.

I'm still having some trouble, however.

The following code works correctly with the jax backend, but with tensorflow does the following:

```
import os

os.environ['KERAS_BACKEND'] = 'tensorflow'
from keras_core import ops

print(ops.sqrt(ops.arange(10)))
```

Throws:

```
  File "keras_core_experiments\repro_2.py", line 6, in <module>
    print(ops.sqrt(ops.arange(10)))
  File "keras_core_experiments\venv\lib\site-packages\keras_core\src\ops\numpy.py", line 5274, in sqrt
    return backend.numpy.sqrt(x)
  File "keras_core_experiments\venv\lib\site-packages\keras_core\src\backend\tensorflow\numpy.py", line 644, in sqrt
    return tfnp.sqrt(x)
  File "keras_core_experiments\venv\lib\site-packages\tensorflow\python\ops\numpy_ops\np_math_ops.py", line 615, in sqrt
    return _scalar(math_ops.sqrt, x, True)
  File "keras_core_experiments\venv\lib\site-packages\tensorflow\python\ops\numpy_ops\np_math_ops.py", line 599, in _scalar
    x = x.astype(np_dtypes.default_float_type())
  File "keras_core_experiments\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 424, in __getattr__
    raise AttributeError(
AttributeError: EagerTensor object has no attribute 'astype'. 
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()
      . Did you mean: 'dtype'?
```

**Comment by sachinprasadhs** [comment]
@lbortolotti , This is working fine in the Keras 3.0.2, please find the working Gist attached [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/f276738b1d8d6385629ce22422e60960/18400.ipynb)
