### ISSUE TITLE
'Model' object has no attribute 'in_multi_worker_mode'

### ISSUE THREAD

**Issue by Charlie4zc** [keras-team/keras#13258]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  tf-nightly-gpu
- Keras version:  2.2.5
- Python version:  3.7
- CUDA/cuDNN version:  9.2/7.0
- GPU model and memory: Nvidia gtx 1080 

I think keras is imcompatible with tf-nightly-gpu since it works fine with py36/tf 1.13/keras.
Is there any resolution for this problem?

**Comment by SachitNayak** [comment]
I'm facing this error too... Here is my stacktrace: (Apparently downgrading to tf 1.14.0 solves the issue it seems)

Train on 4710 samples, validate on 1571 samples
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-6a9c5f74b291> in <module>()
----> 1 full_model.fit([co_X_train, X_train], [y_train], callbacks=[cp_callback], epochs=TOTAL_EPOCHS, batch_size=BATCH_S, validation_split=0.25)

4 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
   1176                                         steps_per_epoch=steps_per_epoch,
   1177                                         validation_steps=validation_steps,
-> 1178                                         validation_freq=validation_freq)
   1179 
   1180     def evaluate(self,

/usr/local/lib/python3.6/dist-packages/keras/engine/training_arrays.py in fit_loop(model, fit_function, fit_inputs, out_labels, batch_size, epochs, verbose, callbacks, val_function, val_inputs, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps, validation_freq)
    133         'metrics': callback_metrics or [],
    134     })
--> 135     callbacks._call_begin_hook('train')
    136     callbacks.model.stop_training = False
    137     for cbk in callbacks:

/usr/local/lib/python3.6/dist-packages/keras/callbacks.py in _call_begin_hook(self, mode)
    101         """Helper function for on_{train|test|predict}_begin methods."""
    102         if mode == _TRAIN:
--> 103             self.on_train_begin()
    104         elif mode == _TEST:
    105             self.on_test_begin()

/usr/local/lib/python3.6/dist-packages/keras/callbacks.py in on_train_begin(self, logs)
    217         """
    218         for callback in self.callbacks:
--> 219             callback.on_train_begin(logs)
    220 
    221     def on_train_end(self, logs=None):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py in on_train_begin(self, logs)
    903   def on_train_begin(self, logs=None):
    904     # pylint: disable=protected-access
--> 905     if self.model._in_multi_worker_mode():
    906       # MultiWorkerTrainingState is used to manage the training state needed
    907       # for preemption-recovery of a worker in multi-worker training.

AttributeError: 'Model' object has no attribute '_in_multi_worker_mode'

**Comment by Ginok1** [comment]
I had the same issue. Downgrading to tf 1.14.0 solved it for me as well.

The issue first appeared for me when i tried to document the learning process by using callbacks.
Without callbacks tf 1.15.0 worked as well.

**Comment by sharkdeng** [comment]
I got this error when the mixed usage of Keras API and tensorFlow.keras API. 
For example:
```
from keras.models import Model
from TensorFlow.keras.callbacks import ReduceLROnPlateau
```

**Comment by Hemanthkumar2112** [comment]
This error may occurs if you trying to use or combine tensorflow(tf) with keras package or layers inside a model or at while compiling a model
for example simply instead of using
 `tf.keras.callbacks.ModelCheckpoint()`
 `tf.keras.callbacks.CSVLogger`
then remove tf write the code as 
`keras.callbacks.ModelCheckpoint()`
`keras.callbacks.CSVLogger`


> happy coding

**Comment by patchy631** [comment]
@Hemanthkumar2112 thanks man. Worked for me with tf-gpu==1.15.0
